### ISSUE TITLE
Documentation on the visualization specification renderer

### ISSUE THREAD

**Issue by peter-gy** [cmudig/draco2#341]
Hi,

I have been doing a quite thorough exploration of the codebase as well as the documentation, however, I failed to find any concrete details on how the example charts are rendered from the specifications generated by the tool. In the intro of the [Example Charts](https://dig.cmu.edu/draco2/facts/examples.html) section of the docs, it is mentioned that *"The specification is inspired by [Vega-Lite](https://vega.github.io/vega-lite/)"*, however, as far as I see, it is not compatible with its latest version. 

Am I missing something, or is the renderer for the specification still a private work & research in progress?

**Comment by Zehua-Zeng** [comment]
Hi, we don't have the code for translating Draco grammar to Vega-lite specifications yet.

**Comment by peter-gy** [comment]
I see, thanks a lot for the quick response.

**Comment by domoritz** [comment]
Yes, that's right. Let's consider adding one in https://github.com/cmudig/draco2/issues/342
