### ISSUE TITLE
Book examples only include code, missing rendered image

### ISSUE THREAD

**Issue by dylancashman** [cmudig/draco2#525]
The book examples (i.e. https://dig.cmu.edu/draco2/facts/encoding.html#example) only include the example code, but don't include the image that they would generate.  I think they'd be much more useful with the visual demonstration of what they produce.

**Comment by JunranY** [comment]
We included some rendered examples here: [chart examples](https://dig.cmu.edu/draco2/facts/examples.html). 
Other example code (including the encoding examples) are describing components of the specification format. 
Most of them can be used as partial input to the recommender, but cannot be directly rendered because they are not complete.

**Comment by dylancashman** [comment]
Ultimately, it is a point of preference, but I still believe that the examples provided would be much more helpful with in-line example charts, especially for someone who is not familiar with vega-lite already.  Without the images, they aren't particularly helpful and seem to be more verbose than needed.

For example, on the page I linked, there are two examples with only the final line differing between them:

```
entity(field,root,temperature).
attribute((field,name),temperature,temperature).
attribute((field,type),temperature,number).

entity(encoding,m,e1).
attribute((encoding,channel),e1,x).
attribute((encoding,field),e1,temperature).
attribute((encoding,aggregate),e1,mean).
```

```
entity(field,root,temperature).
attribute((field,name),temperature,temperature).
attribute((field,type),temperature,number).

entity(encoding,m,e1).
attribute((encoding,channel),e1,x).
attribute((encoding,field),e1,temperature).
attribute((encoding,binning),e1,10).
```

This would be better illustrated having maybe just the last line for each, and then an example for each where the temperature mean is showed vs. the binned temperature.

Anyway, I'm happy to close the issue if the decision is that there aren't plans to add in-line examples throughout the documentation pages.  I had raised the issue because I suspected it was some sort of rendering error.

**Comment by domoritz** [comment]
Thank you for looking at Draco 2 and filing the issue. The examples in the specific facts pages are only examples of the specific thing we look at. As Junran said, they are not intended to be complete. Also note that Draco can support more than Vega-Lite so I think it makes sense not to render them here. 

I agree the example can be improved and we could add more comments. We are always happy to look at prs. However, I think in this case we don't want to add renderings.
