### ISSUE TITLE
Pyodide release not working

### ISSUE THREAD

**Issue by domoritz** [cmudig/draco2#802]
https://github.com/cmudig/draco2/actions/runs/7750965948/job/21138048118 shows that we tried to publish 2.0.0 even though it should be 2.0.1.

**Comment by peter-gy** [comment]
A brief summary of the problem:
- the npm package version comes from the Pyodide distro’s `package.json`
- The `package.json` is updated only upon distro rebuild
- Previously we only triggered the rebuild of the distro when a source file of `poetry.lock` changed. This was a mistake on my part, I assumed that whenever we change the version in `pyproject.toml` the `poetry.lock` is updated and triggers the distro rebuild
- When releasing we used a prebuilt distro and its `package.json` still had version `2.0.0`

The fix introduced in #803 ensures we rebuild the distro whenever the `pyproject.toml` is modified. This way we’ll surely sync the package.json with the version defined in `pyproject.toml`.
