### ISSUE TITLE
Using AltairRenderer in pyodide enviornment

### ISSUE THREAD

**Issue by jiwnchoi** [cmudig/draco2#884]
Hello, I'm currently working on a project using draco-pyodide.

I imported AltairRenderer to convert the recommended visualization to Vega-Lite, but I'm encountering the following error. (This error appears not only in the pyodide console you provided but also in my source code.)

<img width="1121" alt="image" src="https://github.com/user-attachments/assets/05d0123d-2a19-4799-8913-d2be615eaf82">

In the released tarball, the version of pydantic is 2.4.2, but as shown in the attached image, version 1.10.7 of pydantic is loaded in the environment. I think this might be the cause of the problem.

How can I resolve this issue?

Thank you for developing such an amazing library.

**Comment by domoritz** [comment]
I'm not sure what's going on and would appreciate help with fixing this.
